In [3]:
import pandas as pd

df = pd.read_csv('extracted_job_data.csv')
df.head()

,Job Title,Job Description,Skills,Source
0,Need expert Virtual Assistant for account help...,We are looking for a highly experienced and de...,"eBay, Amazon",jobs.json
1,Deutsche Darsteller:innen für Business-Testimo...,Beschreibung:\nWir sind ein deutsches Start-up...,"Female, Male, Senior Adult, German, English, M...",jobs.json
2,Senior Dev - NFT Marketplace,We’re looking for a talented full stack blockc...,"Blockchain Architecture, JavaScript",jobs.json
3,Prospect List/Sourcing Specialist for High-Vol...,We are looking for an experienced Prospect Lis...,"Prospect List, Lead Generation, Market Researc...",jobs.json
4,Long-Term Web Designer (WordPress) with Strong...,We’re looking to build a long-term relationshi...,"Website Redesign, Custom Web Design, Theme Cus...",jobs.json

In [4]:
df[df['Source'] == 'linkedin_jobs.json'].head()

,Job Title,Job Description,Skills,Source
200,Data Engineer,Cybage is an information technology company sp...,"Offshore Software Development , ProductEnginee...",linkedin_jobs.json
201,Data Scientist-LLM Engineer_4+yrs,"At Zorba AI, we harness the power of Generativ...","Data Analytics, Data vizualization, Statistica...",linkedin_jobs.json
202,Data Scientist-LLM Engineer_4+yrs,"At Zorba AI, we harness the power of Generativ...","Data Analytics, Data vizualization, Statistica...",linkedin_jobs.json
203,"Data Engineer - Azure, Airflow, PySpark",NaN,NaN,linkedin_jobs.json
204,Data Engineer,"At The Value Maximizer, we empower businesses ...",NaN,linkedin_jobs.json

In [5]:
df.isna().sum()

Job Title           0
Job Description     8
Skills             34
Source              0
dtype: int64

In [6]:
df[df['Skills'].isnull()].head()

,Job Title,Job Description,Skills,Source
47,Simple modifications for a webpage,I need simple modifications on existing webpag...,NaN,jobs.json
156,Professional Presentation Design for Investmen...,"Hello, I need a professional and clean PowerPo...",NaN,2025-08-20 7P.M..json
203,"Data Engineer - Azure, Airflow, PySpark",NaN,NaN,linkedin_jobs.json
204,Data Engineer,"At The Value Maximizer, we empower businesses ...",NaN,linkedin_jobs.json
205,Data Engineer,"At The Value Maximizer, we empower businesses ...",NaN,linkedin_jobs.json

In [7]:
df1 = df.dropna()
df1.isna().sum()

Job Title          0
Job Description    0
Skills             0
Source             0
dtype: int64

In [8]:
df1.shape

(266, 4)

In [9]:
df1 = df1.drop("Source",axis=1)
df1.head()

,Job Title,Job Description,Skills
0,Need expert Virtual Assistant for account help...,We are looking for a highly experienced and de...,"eBay, Amazon"
1,Deutsche Darsteller:innen für Business-Testimo...,Beschreibung:\nWir sind ein deutsches Start-up...,"Female, Male, Senior Adult, German, English, M..."
2,Senior Dev - NFT Marketplace,We’re looking for a talented full stack blockc...,"Blockchain Architecture, JavaScript"
3,Prospect List/Sourcing Specialist for High-Vol...,We are looking for an experienced Prospect Lis...,"Prospect List, Lead Generation, Market Researc..."
4,Long-Term Web Designer (WordPress) with Strong...,We’re looking to build a long-term relationshi...,"Website Redesign, Custom Web Design, Theme Cus..."

In [10]:
from langchain_ollama import OllamaEmbeddings

embeddings = OllamaEmbeddings(model="nomic-embed-text")

In [11]:
embeddings.embed_query("eBay, Amazon")

[-0.011110215,
 0.058854077,
 -0.1863685,
 -0.013548086,
 0.06414376,
 0.016088594,
 0.0037181703,
 0.016492162,
 0.04957907,
 0.018390562,
 0.019274926,
 -0.034814,
 0.06343659,
 -0.011338479,
 -0.003863281,
 0.017807512,
 0.01246681,
 -0.060531132,
 -0.001343508,
 0.071667925,
 0.01278204,
 -0.05052858,
 -0.056469664,
 0.02948456,
 0.048430387,
 -0.023241859,
 0.001956972,
 0.053386632,
 0.04412774,
 -0.0020476417,
 0.015267863,
 -0.0059988433,
 0.0149097005,
 -0.00078445685,
 -0.015278878,
 -0.038483057,
 0.044718865,
 0.049477555,
 -0.03467927,
 0.04503753,
 0.05935836,
 0.00021418648,
 0.015550148,
 0.005367613,
 0.08264185,
 -0.019992653,
 0.017779566,
 0.03359867,
 0.10324592,
 -0.022279536,
 0.070401594,
 -0.011570382,
 -0.013557426,
 -0.068906486,
 0.008263951,
 -0.019446373,
 -0.01249008,
 0.052101392,
 -0.015045945,
 0.027037939,
 0.07783262,
 0.02107258,
 0.03554407,
 0.07481638,
 0.06925235,
 -0.036611956,
 -0.012955862,
 0.06442587,
 0.012304017,
 -0.049309615,
 0.030508438,
 -0.011421964,
 0.06233843,
 -0.00059338514,
 0.010354322,
 -0.01725037,
 -0.037087966,
 -0.027051724,
 -0.028670931,
 -0.005602133,
 0.04387082,
 -0.0065843686,
 0.034714878,
 -0.0069079585,
 0.06019106,
 -0.01686722,
 -0.014895764,
 0.005335164,
 -0.01162227,
 -0.011090359,
 -0.017259484,
 0.011734779,
 0.031291436,
 0.046743773,
 -0.0034742611,
 0.023488363,
 -0.023534352,
 -0.007851623,
 -0.024035469,
 -0.05221329,
 -0.006551524,
 -0.0056236926,
 0.03158887,
 -0.04089737,
 0.083249696,
 0.012240818,
 0.0322495,
 -0.009529719,
 -0.024499534,
 -0.027897319,
 -0.021125365,
 0.046773523,
 -0.043446146,
 -0.024556404,
 -0.041869067,
 0.019897906,
 0.017878588,
 -0.05041229,
 0.048350707,
 0.034505032,
 0.042598158,
 -0.029260766,
 -0.022244679,
 0.03871059,
 -0.023788838,
 0.0067163445,
 -0.045477416,
 0.007587624,
 -0.029406797,
 0.003525984,
 0.011305734,
 -0.0073037487,
 0.013159785,
 -0.013411949,
 0.004116527,
 0.042277955,
 -0.014584138,
 -0.014525245,
 0.022916753,
 0.061464805,
 0.022686161,
 0.036250927,
 0.005070483,
 0.015089793,
 -0.053717963,
 -0.024331413,
 0.054722603,
 -0.013555962,
 9.7454045e-05,
 0.00899806,
 -0.028144082,
 0.08885916,
 -0.0070713884,
 0.0889073,
 0.015353391,
 0.0072797034,
 0.0045552133,
 -0.04618796,
 0.038845498,
 0.004250798,
 -0.00950786,
 -0.0020746593,
 -0.019126225,
 0.08941501,
 0.02330913,
 -0.0062521547,
 -0.008994772,
 0.02084909,
 0.015379466,
 0.028014882,
 -0.026584167,
 -0.01088226,
 -0.0044859154,
 0.022291327,
 0.026901772,
 -0.035588883,
 0.014486467,
 -0.04894293,
 0.022054002,
 -0.08674594,
 -0.020621585,
 -0.036854208,
 0.009247048,
 0.069179475,
 -0.0058563747,
 -0.0073152557,
 -0.008647644,
 -0.024536705,
 -0.013914106,
 0.01461571,
 -0.01731515,
 0.081824854,
 -0.07277889,
 -0.04633257,
 -0.050827146,
 -0.03478618,
 0.025242964,
 0.0383861,
 0.022597382,
 0.006996913,
 -0.003167411,
 -0.0073634638,
 -0.07736847,
 0.024250153,
 -0.044979718,
 0.036881577,
 -0.013602578,
 0.009277654,
 -0.007755081,
 -0.01777229,
 0.029682992,
 -0.03945211,
 0.0055483105,
 -0.0030099428,
 -0.0016280285,
 0.030967914,
 0.017584167,
 -0.05056118,
 -0.01036323,
 -0.021625284,
 0.040833246,
 0.026163565,
 0.016651113,
 -0.057984784,
 0.052445967,
 -0.031714197,
 -0.03675435,
 0.036730606,
 -0.012696194,
 0.0069475975,
 -0.017651785,
 -0.036649186,
 0.027008552,
 0.024081519,
 0.021242473,
 0.06703942,
 -0.007349375,
 0.005836237,
 -0.008568088,
 0.054242045,
 0.010012039,
 0.04858118,
 -0.03773587,
 -0.021463593,
 -0.04014611,
 -0.021072673,
 -0.028601862,
 -0.0065660183,
 0.005480996,
 0.030123599,
 -0.0043423767,
 0.041980464,
 -0.007279104,
 0.02229315,
 0.042259023,
 0.010607693,
 -0.023644725,
 0.0389962,
 0.02560272,
 -0.05774817,
 0.0033668922,
 -0.030283278,
 0.07796566,
 -0.02001834,
 -0.026944708,
 -0.00865461,
 -0.04694923,
 -0.008326448,
 0.020422079,
 -0.023103032,
 -0.0040950626,
 -0.01668419,
 0.013317957,
 0.032135323,
 -0.010828971,
 -0.015537738,
 0.09379394,
 -0.04700462,
 -0.0146003915,
 0.0030112502,
 -0.041283254,
 -0.001565297,
 0.025190298,
 0.044996593,
 0.015933909,
 0.031839468,
 -0.0042111278,
 0.037683498,
 -0.01590264,
 0.0343875,
 -0.006555967,
 -0.0057606758,
 -0.02235225,
 -0.037710454,
 -0.019607523,
 0.045729425,
 0.058456954,
 -0.035108197,
 -0.027120179,
 -0.039012436,
 0.014777267,
 -0.0062562376,
 0.09538264,
 0.09171295,
 -0.004480672,
 0.03304922,
 0.037622746,
 0.018721797,
 0.066232316,
 -0.011330398,
 -0.020184262,
 0.022063019,
 -0.022359211,
 0.01067359,
 -0.051184405,
 -0.011799235,
 0.049257394,
 0.008984358,
 0.030974148,
 7.960877e-05,
 -0.019492226,
 -0.008065798,
 -0.029004546,
 -0.06952326,
 -0.021739637,
 0.012815289,
 -0.00878278,
 -0.044812318,
 -0.019129816,
 -0.044744566,
 -0.03686481,
 0.032063127,
 -0.0018724075,
 -0.03867152,
 -0.024664009,
 0.04370472,
 -0.021851953,
 0.03373533,
 0.02556866,
 0.048795592,
 0.071460634,
 -0.014245219,
 0.03025908,
 -0.026788902,
 -0.03120338,
 0.009004429,
 0.03192239,
 -0.034845363,
 0.01695669,
 -0.021841325,
 -0.061203565,
 0.00015682633,
 0.038707178,
 0.048917625,
 0.022072908,
 -0.00030867447,
 0.023306848,
 0.028418884,
 0.023132097,
 -0.0012780982,
 0.030576216,
 0.0056951293,
 0.012734557,
 -0.057350595,
 -0.011071338,
 -0.03757469,
 0.028887233,
 -0.051787004,
 0.05018568,
 0.005253711,
 0.020435914,
 0.035885066,
 0.030598009,
 0.030119527,
 -0.0008043058,
 0.041780617,
 -0.02288361,
 -0.019461492,
 -0.031060394,
 0.011575674,
 0.025342936,
 -0.020900533,
 5.3513413e-05,
 0.015769247,
 -0.005596761,
 -0.024526047,
 0.0024794831,
 -0.03680329,
 -0.053758845,
 -0.0068923375,
 -0.015531598,
 -0.022711117,
 -0.03916448,
 -0.0015550201,
 0.005735664,
 -0.030528735,
 0.046296533,
 -0.027171362,
 0.0058320817,
 0.033327296,
 -0.011063018,
 -0.0457262,
 0.0078216605,
 -0.06247732,
 0.024465133,
 0.04503926,
 -0.0826925,
 -0.041640192,
 0.060444124,
 0.02474694,
 0.009804916,
 0.0147598535,
 -0.025427083,
 -0.01631526,
 -0.0065809046,
 0.03566378,
 0.023117423,
 -0.005607405,
 0.0077711907,
 -0.03261842,
 0.04997956,
 -0.008922058,
 0.051374074,
 0.001027363,
 0.0036014125,
 0.038442202,
 0.035007417,
 0.05288991,
 -0.017708626,
 -0.048933376,
 -0.048939794,
 -0.0060398113,
 -0.01988466,
 -0.014609889,
 -0.0082694525,
 0.03596436,
 0.0127626825,
 0.004465768,
 0.05622749,
 0.0003810953,
 0.07475318,
 0.025167428,
 -0.048967518,
 -0.026789429,
 -0.020909747,
 0.1088461,
 0.067765765,
 0.01859513,
 -0.005278386,
 -0.060952455,
 0.011799699,
 -0.05837437,
 0.042980928,
 -0.014471681,
 0.02558029,
 -0.046891034,
 0.048802856,
 0.02684911,
 0.028629856,
 0.020085094,
 0.011894828,
 0.00874645,
 -0.057699528,
 0.009060962,
 0.012881623,
 -0.028441058,
 -0.04164685,
 -0.00243767,
 -0.017055724,
 0.036406744,
 -0.011355563,
 0.011367473,
 0.042630114,
 0.018492868,
 -0.040522423,
 0.04721486,
 -0.010710791,
 -0.007970012,
 -0.033373516,
 0.010882592,
 -0.038044654,
 -0.018676277,
 -0.04847445,
 -0.056326497,
 0.02526132,
 0.03362048,
 0.015706142,
 0.03439206,
 0.045835387,
 0.042126656,
 0.014224542,
 -0.025126556,
 -0.029854191,
 -0.015565381,
 -0.0002803813,
 0.009074064,
 -0.068139195,
 0.023929648,
 0.051306576,
 -0.010010717,
 0.020414554,
 0.02874213,
 -0.050785605,
 -0.0063587963,
 0.033953164,
 -0.054811288,
 0.021728648,
 0.008200416,
 0.0043173963,
 0.0055140187,
 -0.029582003,
 0.0140059395,
 -0.052669574,
 0.04478821,
 0.03424591,
 -0.005977787,
 -0.0163257,
 0.017810453,
 -0.010854856,
 0.043410517,
 0.009593142,
 -0.039695095,
 0.00035402138,
 -0.01080111,
 -0.032251935,
 -0.013188508,
 -0.047203023,
 0.044483874,
 -0.013842896,
 -0.01625206,
 0.040412556,
 0.04611214,
 -0.04165831,
 -0.015943753,
 0.0035231193,
 -0.021235622,
 -0.052427787,
 0.008179908,
 0.037984002,
 0.011853281,
 -0.010943639,
 -0.044382904,
 0.0012653016,
 -0.02314368,
 0.013224032,
 -0.03777827,
 0.009487826,
 -0.08041891,
 -0.0064394698,
 -0.016329175,
 0.07345876,
 -0.073552206,
 -0.0032821016,
 -0.012760234,
 -0.02500256,
 -0.03734553,
 -0.047017347,
 0.012430407,
 0.004578044,
 0.0026094203,
 0.015504971,
 -0.0024193139,
 0.057050575,
 0.010747139,
 -0.0063605285,
 -0.017011413,
 0.0014969562,
 -0.024079433,
 0.004843008,
 0.04197002,
 -0.071003914,
 -0.048137713,
 -0.07077782,
 0.007613144,
 0.049688052,
 -0.03373225,
 0.008648475,
 -0.0584449,
 -0.0071128183,
 -0.041228943,
 0.018087002,
 -0.052513324,
 0.027582945,
 0.038640972,
 -0.0018755931,
 0.0022561706,
 0.008461841,
 -0.03608823,
 0.030272529,
 -0.044965237,
 -0.026741998,
 -0.015761184,
 -0.016880803,
 -0.053187385,
 -0.029666377,
 0.03726279,
 -0.030115621,
 -0.07259212,
 0.02060258,
 -0.027856335,
 0.0012948075,
 -0.0003841624,
 0.054660626,
 -0.020423163,
 0.014457569,
 0.022111675,
 0.008873469,
 0.010513953,
 0.0020912366,
 0.026089564,
 -0.0090154875,
 -0.030064525,
 -0.020500982,
 -0.0713029,
 0.042808324,
 -0.0426503,
 0.064208396,
 -0.07719007,
 -0.05129754,
 -0.011015773,
 0.010127763,
 -0.06620611,
 0.011923253,
 0.021194683,
 0.04711345,
 0.0012172917,
 -0.057283677,
 -0.07040098,
 0.017584285,
 0.06190375,
 0.019799143,
 0.0072312127,
 -0.015216821,
 -0.043210983,
 -0.057111572,
 0.007696201,
 -0.07515718,
 0.021979587,
 0.024848469,
 -0.009978589,
 0.039881967,
 -0.016510215,
 0.0053078863,
 0.048725035,
 0.021865841,
 0.00055342336,
 0.076409586,
 0.017338905,
 0.054151002,
 -0.0036426687,
 0.054965857,
 0.09524234,
 0.005664892,
 0.017384987,
 0.02343273,
 0.023890084,
 0.041606136,
 -0.00891594,
 -0.03989662,
 -0.009550593,
 0.02864321,
 0.04177721,
 -0.042340722,
 0.034695525,
 0.0316408,
 -0.036244586,
 -0.08399875,
 -0.036516566,
 -0.027830927,
 0.000879872,
 0.036265332,
 0.005938439,
 -0.032853063,
 -0.03760404,
 0.03209938,
 0.09726709,
 0.031784996,
 0.00044479384,
 -0.05211211,
 0.0040853913,
 -0.013188362,
 0.028537812,
 -0.05199702,
 -0.01977085,
 0.01550905,
 -0.022633886,
 0.02167125,
 0.006688228,
 -0.017766846,
 -0.040803097,
 -0.0062902635,
 -0.10533625,
 -0.0113319,
 -0.006934637,
 -0.011409014,
 -0.014305881,
 -0.041980848,
 -0.075692475,
 -0.05619758,
 -0.0045236107,
 -0.050037548,
 0.027168594,
 0.006579951,
 -0.00088084734,
 -0.024940053,
 -0.015150356,
 0.00822712,
 0.03394796,
 0.0016441571,
 0.016169602,
 0.022079097,
 -0.025447544,
 0.026709432,
 0.043750767,
 0.015160403,
 -0.023087086,
 0.015338138,
 -0.05365735,
 -0.04628547,
 0.011406346,
 0.05153622,
 -0.013066673,
 -0.050203707,
 -0.0068333293,
 -0.070148066,
 -0.04949377,
 0.016349675,
 -0.03017666,
 0.048864715,
 -0.014613006,
 0.009396553,
 0.008549353,
 -0.004412238,
 0.05213934,
 -0.037866995,
 0.030995477,
 -0.049111776,
 -0.06805477,
 -0.033261202,
 -0.0080229845,
 -0.032584447,
 -0.07651726,
 -0.033988804,
 0.04916107,
 0.008093659,
 -0.040004402,
 -0.011801927,
 -0.015387837,
 0.026753565,
 0.011367301,
 -0.0011895808,
 -0.06876972,
 -0.033397783,
 -0.023397736,
 -0.046591185,
 0.032833863,
 0.012070922,
 0.0699826,
 0.065398574,
 0.044364214,
 0.01846632,
 -0.06495148,
 0.030464664,
 -0.031124447,
 -0.026590427,
 -0.0126633905,
 -0.040528797,
 -0.010623658]

In [12]:
df1.shape

(266, 3)

In [13]:
df2 = df1.copy()

df2['job_title_vector'] = df1['Job Title'].apply(lambda x: embeddings.embed_documents([x])[0])
df2['job_description_vector'] = df1['Job Description'].apply(lambda x: embeddings.embed_documents([x])[0])
df2['skills_vector'] = df1['Skills'].apply(lambda x: embeddings.embed_documents([x])[0])

In [14]:
df2.head()

,Job Title,Job Description,Skills,job_title_vector,job_description_vector,skills_vector
0,Need expert Virtual Assistant for account help...,We are looking for a highly experienced and de...,"eBay, Amazon","[-0.03432415, 0.0688692, -0.17689398, 0.010752...","[-0.03281193, 0.06299572, -0.1882647, -0.02311...","[-0.011110215, 0.058854077, -0.1863685, -0.013..."
1,Deutsche Darsteller:innen für Business-Testimo...,Beschreibung:\nWir sind ein deutsches Start-up...,"Female, Male, Senior Adult, German, English, M...","[0.0002044781, 0.044697683, -0.2167915, 0.0442...","[0.035952438, 0.045943994, -0.18886392, 0.0227...","[0.0044593145, -0.03354234, -0.18568496, -0.00..."
2,Senior Dev - NFT Marketplace,We’re looking for a talented full stack blockc...,"Blockchain Architecture, JavaScript","[-0.022473685, 0.047376215, -0.19609861, -0.05...","[0.00015799973, 0.11287172, -0.14360082, -0.02...","[-0.032951277, 0.06769134, -0.11452641, -0.054..."
3,Prospect List/Sourcing Specialist for High-Vol...,We are looking for an experienced Prospect Lis...,"Prospect List, Lead Generation, Market Researc...","[-0.037890784, 0.06805323, -0.17732812, -0.024...","[-0.026088659, 0.0607295, -0.17025319, -0.0488...","[-0.033584367, 0.036634166, -0.19281477, -0.01..."
4,Long-Term Web Designer (WordPress) with Strong...,We’re looking to build a long-term relationshi...,"Website Redesign, Custom Web Design, Theme Cus...","[-0.0637804, 0.09495902, -0.18783227, 0.014851...","[-0.030906245, 0.109356344, -0.13780257, 0.003...","[-0.058860835, 0.086276375, -0.18779542, -0.00..."

In [15]:
df2.to_csv('job_embeddings.csv', index=False)